PROGRAM  = yourMom.exe
CXX      = g++

CSRC = $(wildcard *.cpp)

CFLAGS   = -g --std=c++20 
INCLUDES = -I./include
#LIBS     =
#LDFLAGS  =

target : 
	$(CXX) $(INCLUDES) $(CFLAGS) $(CSRC) -o $(PROGRAM)
